WebStore/administration/urls.py
from django.urls import path

from . import views

app_name = 'administration'
urlpatterns = [
    path('configuration/', views.ConfigurationDetail.as_view(), name='configuration'),
    path('configuration/update/', views.ConfigurationUpdate.as_view(), name='configuration_update'),
    
    path('product/', views.ProductIndex.as_view(), name='products'),
    path('product/create/', views.ProductCreate.as_view(), name='product_create'),
    path('product/<int:pk>/update/', views.ProductUpdate.as_view(), name='product_update'),
    path('product/<int:pk>/delete/', views.ProductDelete.as_view(), name='product_delete'),
    
    path('category/', views.CategoryIndex.as_view(), name='categories'),
    path('category/create/', views.CategoryCreate.as_view(), name='category_create'),
    path('category/<int:pk>/', views.CategoryDetail.as_view(), name='category_detail'),
    path('category/<int:pk>/update/', views.CategoryUpdate.as_view(), name='category_update'),
    path('category/<int:pk>/delete/', views.CategoryDelete.as_view(), name='category_delete'),
    
    path('order/', views.OrderIndex.as_view(), name='orders'),
    path('order/create/', views.OrderCreate.as_view(), name='order_create'),
    path('order/<int:pk>/', views.OrderDetail.as_view(), name='order_detail'),
    path('order/<int:pk>/update/', views.OrderUpdate.as_view(), name='order_update'),
    path('order/<int:order_id>/next-step/', views.order_next_step, name='order_next_step'),

    path('promo/', views.PromoIndex.as_view(), name='promos'),
    path('promo/create/', views.PromoCreate.as_view(), name='promo_create'),
    path('promo/<int:pk>/', views.PromoDetail.as_view(), name='promo_detail'),
    path('promo/<int:pk>/update-type/', views.PromoTypeUpdate.as_view(), name='promo_type_update'),
    path('promo/<int:pk>/update-content/', views.PromoContentUpdate.as_view(), name='promo_content_update'),
]

WebStore/order/urls.py
from django.urls import path

from . import views

app_name = 'order'
urlpatterns = [
    path('cart/', views.cart, name='cart'),
    path('cart-item-edit/', views.cart_item_edit, name='cart_item_edit'),
    path('<int:product_id>/edit-cart-item/', views.cart_item_edit, name='cart_item_edit'),
    path('', views.IndexView.as_view(), name='index'),
    # path('<int:order_id>/', views.order_detail, name='detail'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('create/', views.order_create, name='create'),
    path('next-step/', views.next_step, name='next_step'),
    path('<int:pk>/edit-remittance-account/', views.EditRemittanceAccount.as_view(), name='edit_remittance_account'),
    path('<int:order_id>/promo-apply/', views.promo_apply, name='promo_apply'),
    path('<int:order_id>/promo-remove/', views.promo_remove, name='promo_remove'),
]

WebStore/products/urls.py
from django.urls import path

from . import views

app_name = 'products'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
]

WebStore/templates/administration_base.html
{% load static %}
<head>
    <title>WebStore Administration</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+TC&display=swap" rel="stylesheet">    
    <link rel="stylesheet" href="{% static 'Webstore/css/style_administration.css' %}">
    <!-- link rel="icon" href="{{ site_logo_small_url }}" type="image/icon type" -->
    <script src="https://kit.fontawesome.com/dfb9609c56.js" crossorigin="anonymous"></script>
</head>

<body>
    <div class="sidebar">
        <a href="{% url 'administration:products' %}" class="{{ active_products }}">
            <nav><i class="fas fa-star"></i>產品</nav>
        </a>
        <a href="{% url 'administration:orders' %}" class="{{ active_orders }}">
            <nav><i class="fas fa-stream"></i>訂單</nav>
        </a>
        <a href="{% url 'administration:promos' %}" class="{{ active_promo }}">
            <nav><i class="fas fa-tag"></i>優惠碼</nav>
        </a>
        <a href="{% url 'administration:configuration' %}" class="{{ active_configuration }}">
            <nav><i class="fas fa-cog"></i>設定</nav>
        </a>
        <a href="{% url 'products:index' %}" target="_blank" class="">
            <nav><i class="fas fa-chevron-circle-right"></i>造訪您的網站</nav>
        </a>
        <a href="{% url 'logout' %}" class="">
            <nav><i class="fas fa-sign-out-alt"></i>登出</nav>
        </a>
    </div>
    <div class="page-content">
        {% block page-content %}
        {% endblock %}
    </div>
</body>

WebStore/templates/base.html
{% load static %}
<head>
    <title>{{ config.site_name }}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+TC&display=swap" rel="stylesheet">    
    <link rel="stylesheet" href="{% static 'Webstore/css/style.css' %}">
    <link rel="icon" href="{{ config.site_logo_small.url }}" type="image/icon type">
</head>

<body>
    <header class="center">
        <div class="top-nav">
            <div class="nav-logo">
                <a href="{% url 'products:index' %}"><img src="{{ config.site_logo_large.url }}" alt="logo" /></a>
            </div>
            <div class="nav-non-logo">
                <div class="nav-item">
                    <a href="{% url 'products:index' %}">所有產品</a>
                    <a href="{% url 'order:cart' %}">購物車</a>
                    <a href="{% url 'order:index' %}">我的訂單</a>
                    {% if request.user.is_authenticated %}
                    <a href="{% url 'profile' %}">我的帳戶</a>
                        {% if request.user.is_staff %}
                    <a href="{% url 'administration:orders' %}">管理</a>
                        {% endif %}
                    <a href="{% url 'logout' %}">登出</a>
                    {% else %}
                    <a href="{% url 'login' %}">登入</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </header>

    <main class="center">
        {% if config.is_visitable or login_page %}
        <div class="page-content">
            {% block content %}
            {% endblock %}
        </div>
        {% else %}
        <div class="page-content">
            現在無法造訪這個網頁，請稍後再試！
        </div>
        {% endif %}
    </main>

    <footer class="center">
        <div class="page-bottom">
            <div class="container">
                <div class=page-bottom-section>
                    <div class="heavy">
                        選購與了解產品
                    </div>
                    <div class="">
                        <a href="{% url 'products:index' %}">所有產品</a>
                    </div>
                    <div class="">
                        <a href="{% url 'order:cart' %}">購物車</a>
                    </div>
                </div>
                <div class=page-bottom-section>
                    <div class="heavy">
                        帳戶與訂單
                    </div>
                    <div class="">
                        <a href="{% url 'profile' %}">我的帳戶</a>
                    </div>
                    <div class="">
                        <a href="{% url 'order:index' %}">我的訂單</a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="heavy">
                    {{ config.site_name }}
                </div>
                <div class="">
                    聯絡電話：{{ config.manager_contact_phone_no }}
                </div>
                <div class="">
                    電子郵件：{{ config.manager_email }}
                </div>
                <div class="">
                    地址：{{ config.manager_address }}
                </div>
            </div>
            <div class="row">
                <div class="">
                    {{ config.copyright_info }}
                </div>
                <div class="">
                    Designed and powered by Samuel Yu @ NCTU. All rights reserved.
                </div>
            </div>
        </div>
    </footer>


</body>