WebStore/order/urls.py
from django.urls import path

from . import views

app_name = 'order'
urlpatterns = [
    path('cart/', views.cart, name='cart'),
    path('cart-item-edit/', views.cart_item_edit, name='cart_item_edit'),
    path('<int:product_id>/edit-cart-item/', views.cart_item_edit, name='cart_item_edit'),
    path('', views.IndexView.as_view(), name='index'),
    # path('<int:order_id>/', views.order_detail, name='detail'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('create/', views.order_create, name='create'),
    path('next-step/', views.next_step, name='next_step'),
    path('<int:pk>/edit-remittance-account/', views.EditRemittanceAccount.as_view(), name='edit_remittance_account'),
    path('<int:order_id>/promo-apply/', views.promo_apply, name='promo_apply'),
    path('<int:order_id>/promo-remove/', views.promo_remove, name='promo_remove'),
]

WebStore/products/urls.py
from django.urls import path

from . import views

app_name = 'products'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
]

WebStore/products/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    class Meta:
        verbose_name_plural = "categories"
    
    name = models.CharField(max_length=200, verbose_name='類別名稱')

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='類別')
    name = models.CharField(max_length=200, verbose_name='名稱')
    utility = models.CharField(max_length=200, verbose_name='用途')
    ingredient = models.CharField(max_length=200, verbose_name='成分')
    description = models.TextField(blank=True, verbose_name='概覽')
    unit_price = models.IntegerField(default=0, verbose_name='單價')
    is_sellable = models.BooleanField(default=True, verbose_name='上架')
    inventory_quantity = models.IntegerField(default=0, verbose_name='庫存')
    cover_image = models.ImageField(blank=True, verbose_name='封面照片')

    def __str__(self):
        return self.name

class Image(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='產品')
    image = models.ImageField(verbose_name='照片')

WebStore/products/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Product
from administration.models import Configuration

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'products/index.html'

    def get_queryset(self):
        return Product.objects.filter(is_sellable=True)

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['config'] = Configuration.objects.first()
        return context

class DetailView(generic.DetailView):
    model = Product
    template_name = 'products/detail.html'

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context['config'] = Configuration.objects.first()
        return context

    

WebStore/templates/products/detail.html
{% extends 'base.html' %}
{% block content %}

<div class="caption"">
    {{ product.category }}
</div>

<div class="container">
    <div class="top-section">
        <div class="intro">
            <div class="title">
                {{ product }}
            </div>
            <div class="sub-title">
                {{ product.utility }}
            </div>
            <div class="tag price-tag">
                NT$ {{ product.unit_price }} /個
            </div>
            {% if product.inventory_quantity > 0 %}
                <div class="function">
                    <form action="{% url 'order:cart_item_edit' product.id %}" method="post">{% csrf_token %}
                        <input type="hidden" name="product_id" value="{{ product.id }}">
                        <input type="hidden" name="amount" value="1">
                        <input class="add-to-cart button" type="submit" value="加入購物車">
                    </form>
                </div>
            {% else %}
                <div class="tag">
                    很抱歉，此產品目前沒有存貨。
                </div>
            {% endif %}
        </div>
    </div>
    {% if product.cover_image %}
        <div class="top-section">
            <div class="cover-image">
                <img src="{{ product.cover_image.url }}" alt="cover_image" />
            </div>
        </div>
    {% endif %}
</div>


<div class="product-info">
    <div class="title">
        產品資訊
    </div>
    <div class="container-jcleft row">
        <div class="attribute-name">
            概覽
        </div>
        <div class="attribute">
            {{ product.description }}
        </div>
    </div>
    <div class="container-jcleft row">
        <div class="attribute-name">
            成分
        </div>
        <div class="attribute">
            {{ product.ingredient }}
        </div>
    </div>
    <div class="container-jcleft row">
        <div class="attribute-name">
            用途
        </div>
        <div class="attribute">
            {{ product.utility }}
        </div>
    </div>
</div>






<!-- <h1>{{ product }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<p>{{ product.category }}</p>
<p>{{ product.utility }}</p>
<p>{{ product.ingredient }}</p>
<p>{{ product.description }}</p>
<p>{{ product.unit_price }}</p>
<p>{{ product.is_sellable }}</p>
<p>{{ product.inventory_quantity }}</p>

<form action="{% url 'order:cart_item_edit' product.id %}" method="post">{% csrf_token %}
    <input type="hidden" name="product_id" value="{{ product.id }}">
    <input type="number" min="1" name="amount" value="1">
    <input type="submit" value="Add to cart">
</form> -->

<!-- {% if product.cover_image %}
    <img src="{{ product.cover_image.url }}" alt="cover_image" />
{% endif %}
{% for image in product.image_set.all %}
    <img src="{{ image.image.url }}" alt="image" />
{% endfor %}
-->
{% endblock %}

WebStore/templates/products/index.html
{% extends 'base.html' %}
{% block content %}


<div class="caption"">
    所有產品
</div>

<div class="container">
    {% for product in object_list %}
        <div class="card shadow">
            <a href="{% url 'products:detail' product.id %}">
                <div class="card-image">
                    {% if product.cover_image %}
                        <img src="{{ product.cover_image.url }}" alt="cover_image" />
                    {% endif %}
                </div>
                <div class="card-content">
                    <div class="title">
                        {{ product }}
                    </div>
                    <div class="sub-title">
                        {{ product.utility|truncatechars:16 }}
                    </div>
                    <div class="tag price-tag">
                        NT$ {{ product.unit_price }}
                    </div>
                    <div class="function">
                        <form action="{% url 'order:cart_item_edit' product.id %}" method="post">{% csrf_token %}
                            <input type="hidden" name="product_id" value="{{ product.id }}">
                            <input type="hidden" name="amount" value="1">
                            <input class="add-to-cart button" type="submit" value="加入購物車">
                        </form>
                    </div>
                </div>
            </a>
        </div>
    
    {% endfor %}
</div>

{% endblock %}