WebStore/administration/urls.py
from django.urls import path

from . import views

app_name = 'administration'
urlpatterns = [
    path('configuration/', views.ConfigurationDetail.as_view(), name='configuration'),
    path('configuration/update/', views.ConfigurationUpdate.as_view(), name='configuration_update'),
    
    path('product/', views.ProductIndex.as_view(), name='products'),
    path('product/create/', views.ProductCreate.as_view(), name='product_create'),
    path('product/<int:pk>/update/', views.ProductUpdate.as_view(), name='product_update'),
    path('product/<int:pk>/delete/', views.ProductDelete.as_view(), name='product_delete'),
    
    path('category/', views.CategoryIndex.as_view(), name='categories'),
    path('category/create/', views.CategoryCreate.as_view(), name='category_create'),
    path('category/<int:pk>/', views.CategoryDetail.as_view(), name='category_detail'),
    path('category/<int:pk>/update/', views.CategoryUpdate.as_view(), name='category_update'),
    path('category/<int:pk>/delete/', views.CategoryDelete.as_view(), name='category_delete'),
    
    path('order/', views.OrderIndex.as_view(), name='orders'),
    path('order/create/', views.OrderCreate.as_view(), name='order_create'),
    path('order/<int:pk>/', views.OrderDetail.as_view(), name='order_detail'),
    path('order/<int:pk>/update/', views.OrderUpdate.as_view(), name='order_update'),
    path('order/<int:order_id>/next-step/', views.order_next_step, name='order_next_step'),

    path('promo/', views.PromoIndex.as_view(), name='promos'),
    path('promo/create/', views.PromoCreate.as_view(), name='promo_create'),
    path('promo/<int:pk>/', views.PromoDetail.as_view(), name='promo_detail'),
    path('promo/<int:pk>/update-type/', views.PromoTypeUpdate.as_view(), name='promo_type_update'),
    path('promo/<int:pk>/update-content/', views.PromoContentUpdate.as_view(), name='promo_content_update'),
]

WebStore/order/urls.py
from django.urls import path

from . import views

app_name = 'order'
urlpatterns = [
    path('cart/', views.cart, name='cart'),
    path('cart-item-edit/', views.cart_item_edit, name='cart_item_edit'),
    path('<int:product_id>/edit-cart-item/', views.cart_item_edit, name='cart_item_edit'),
    path('', views.IndexView.as_view(), name='index'),
    # path('<int:order_id>/', views.order_detail, name='detail'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('create/', views.order_create, name='create'),
    path('next-step/', views.next_step, name='next_step'),
    path('<int:pk>/edit-remittance-account/', views.EditRemittanceAccount.as_view(), name='edit_remittance_account'),
    path('<int:order_id>/promo-apply/', views.promo_apply, name='promo_apply'),
    path('<int:order_id>/promo-remove/', views.promo_remove, name='promo_remove'),
]

WebStore/products/urls.py
from django.urls import path

from . import views

app_name = 'products'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
]

WebStore/administration/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Configuration(models.Model):
    site_name = models.CharField(max_length=200, verbose_name='網站名稱')
    site_logo_small = models.ImageField(upload_to='administration', verbose_name='網站Logo（小）')
    site_logo_large = models.ImageField(upload_to='administration', verbose_name='網站Logo（大）')
    is_visitable = models.BooleanField(default=True, verbose_name='允許造訪網站')
    is_sellable = models.BooleanField(default=True, verbose_name='允許顧客成立訂單')
    manager_user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='管理員')
    manager_name = models.CharField(max_length=100, verbose_name='管理員姓名')
    manager_contact_phone_no = models.CharField(max_length=20, verbose_name='管理員聯絡電話')
    manager_email = models.CharField(max_length=100, verbose_name='管理員電子郵件信箱')
    manager_address = models.CharField(max_length=200, verbose_name='管理員地址')
    manager_bank_name = models.CharField(max_length=20, verbose_name='收款銀行名稱')
    manager_bank_code = models.CharField(max_length=5, verbose_name='收款銀行代碼')
    manager_receiving_account_name = models.CharField(max_length=30, verbose_name='收款帳戶名稱')
    manager_receiving_account = models.CharField(max_length=30, verbose_name='收款帳號')
    shipping_fee = models.IntegerField(default=60, verbose_name='每筆訂單運費')
    discount_shipping_fee = models.IntegerField(default=2000, verbose_name='滿此金額免運費')
    copyright_info = models.CharField(max_length=200, verbose_name='權利聲明')

class UserProfile(models.Model):
    GENDER_CHOICES = ((0, '先生'), (1, '女士'))

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    gender = models.IntegerField(default=0, choices=GENDER_CHOICES)
    shipping_postal_code = models.CharField(max_length=5, blank=True)
    shipping_address = models.CharField(max_length=200, blank=True)
    contact_phone_no = models.CharField(max_length=20, blank=True)

WebStore/order/models.py
from datetime import datetime
from django.db import models
from django.conf import settings
from products.models import Product
from administration.models import Configuration
from django.utils import timezone


# Create your models here.
class CartItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    amount = models.IntegerField(default=1)

    def __str__(self):
        return str(self.product) + '(' + str(self.amount) + ')'

    def is_valid(self):
        return self.amount <= self.product.inventory_quantity and self.product.is_sellable

    def total_amounts(self):
        return self.product.unit_price * self.amount


class Promo(models.Model):
    DISCOUNT_TYPE_CHOICES = ((0, '總金額折價'), (1, '總金額打折'), (2, '免運費'))
    HAS_LIMIT_CHOICES = ((0, '無'), (1, '有'))

    code = models.CharField(max_length=32, unique=True, verbose_name='優惠代碼')
    used_count = models.IntegerField(default=0, verbose_name='使用次數')
    
    # Discount Type
    discount_type = models.IntegerField(default=0, choices=DISCOUNT_TYPE_CHOICES, verbose_name='優惠類型')
    discount_amount = models.IntegerField(default=0, verbose_name='折價金額')
    discount_ratio = models.DecimalField(default=0.9, max_digits=3, decimal_places=2, verbose_name='打折（比例）')
    discount_limit = models.IntegerField(default=100, verbose_name='最高折價上限')
    
    # Limitations
    has_total_amount_limit = models.IntegerField(default=0, choices=HAS_LIMIT_CHOICES, verbose_name='消費滿額才可用限制')
    total_amount_limit = models.IntegerField(default=0, verbose_name='消費滿此金額可用')
    
    has_total_count_limit = models.IntegerField(default=0, choices=HAS_LIMIT_CHOICES, verbose_name='使用次數限制')
    total_count_limit = models.IntegerField(default=10, verbose_name='剩餘使用次數')
    
    has_time_limit = models.IntegerField(default=0, choices=HAS_LIMIT_CHOICES, verbose_name='使用時間限制')
    time_limit_start = models.DateTimeField(default=timezone.now, verbose_name='開始有效時間')
    time_limit_expire = models.DateTimeField(default=timezone.now, verbose_name='截止有效時間')
    
    def __str__(self):
        return str(self.code)

    def usage_description(self):
        return self.total_amount_limit_description() + \
               self.discount_type_description() + \
               self.time_limit_description() + \
               self.total_count_limit_description()

    def discount_type_description(self):
        ret = ''
        if self.discount_type == 0:
            ret += '消費金額折扣 NT$' + str(self.discount_amount)
        elif self.discount_type == 1:
            ratio_digits1 = ['零', '一', '二', '三', '四', '五', '六', '七', '八', '九']
            ratio_digits2 = ['', '一', '二', '三', '四', '五', '六', '七', '八', '九']
            discount_str = str(self.discount_ratio)
            ratio_str = ratio_digits1[int(discount_str[2])] + ratio_digits2[int(discount_str[3])] + '折'
            ret += '消費金額' + ratio_str
            ret += '，折抵金額上限NT$ ' + str(self.discount_limit)
            print(str(self.discount_ratio)[2])
        elif self.discount_type == 2:
            ret += '免運費'
        return ret + '。'

    def total_amount_limit_description(self):
        ret = ''
        if self.has_total_amount_limit == 1:
            ret += '消費金額滿NT$ ' + str(self.total_amount_limit)
        else:
            ret += '不限消費金額'
        return ret + '可使用。'

    def time_limit_description(self):
        ret = '使用期限'
        if self.has_time_limit == 1:
            ret += '自' + str(self.time_limit_start) + '至' + str(self.time_limit_expire) + '止'
        else:
            ret += '無限制'
        return ret + '。'

    def total_count_limit_description(self):
        ret = ''
        if self.has_total_count_limit == 1:
            ret += str(self.total_count_limit)
        else:
            ret += '無限制'
        return ret

class Order(models.Model):
    GENDER_CHOICES = ((0, '先生'), (1, '女士'))
    STATUS_CHOICES = ((0, '已初始'), (1, '已成立'), (2, '已確認收到付款'), (3, '已出貨'), (4, '已完成'),
                      (5, '已申請退回'), (6, '已收到退回商品'), (7, '已退款'))
    PAYMENT_CHOICES = ((0, 'ATM匯款'),)
    
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL, verbose_name='使用者')
    user_name = models.CharField(max_length=100, verbose_name='收件人')
    user_gender = models.IntegerField(default=0, choices=GENDER_CHOICES, verbose_name='稱謂')
    user_contact_phone_no = models.CharField(max_length=20, verbose_name='聯絡電話')
    shipping_postal_code = models.CharField(max_length=5, verbose_name='郵遞區號')
    shipping_address = models.CharField(max_length=200, verbose_name='收件地址')
    shipping_fee = models.IntegerField(default=60, verbose_name='運費')
    total_amount = models.IntegerField(verbose_name='總金額')
    status = models.IntegerField(default=0, choices=STATUS_CHOICES, verbose_name='狀態')
    payment = models.IntegerField(default=0, choices=PAYMENT_CHOICES, verbose_name='付款方式')
    remittance_account = models.CharField(blank=True, max_length=5, verbose_name='匯款帳號末五碼')
    is_canceled = models.BooleanField(default=False, verbose_name='已取消')
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name='成立時間')
    promo = models.ForeignKey(Promo, null=True, on_delete=models.SET_NULL, verbose_name='優惠碼')
    promo_code = models.CharField(max_length=32, null=True, verbose_name='優惠代碼')
    discount = models.IntegerField(default=0, verbose_name='優惠')


    def __str__(self):
        return '訂單 ' + str(self.id)

    def cal_shipping_fee(self):
        config = Configuration.objects.first()
        discount_shipping_fee = config.discount_shipping_fee
        if self.cal_subtotal() < discount_shipping_fee:
            return config.shipping_fee
        else:
            return 0

    def cal_subtotal(self):
        subtotal = 0
        for item in self.orderitem_set.all():
            subtotal += item.total_amounts()
        return subtotal

    def cal_total_amounts(self):
        total_amounts = self.shipping_fee
        total_amounts += self.cal_subtotal()
        total_amounts -= self.discount
        return total_amounts if total_amounts > 0 else 0

    def can_use(self, promo):
        if promo.has_total_amount_limit == 1:
            if self.cal_subtotal() < promo.total_amount_limit:
                return False

        if promo.has_time_limit == 1:
            now = timezone.now()
            if not (promo.time_limit_start <= now <= promo.time_limit_expire):
                return False

        if promo.has_total_count_limit == 1:
            if promo.total_count_limit <= 0:
                return False

        return True

    def apply_promo(self, promo):
        if self.promo is not None:
            self.remove_promo()
        
        subtotal = self.cal_subtotal()
        self.promo = promo
        self.promo_code = promo.code
        if promo.discount_type == 0:
            self.discount = promo.discount_amount
            self.discount = subtotal if self.discount > subtotal else self.discount
        elif promo.discount_type == 1:
            self.discount = self.cal_subtotal() * (1 - promo.discount_ratio)
            self.discount = promo.discount_limit if self.discount > promo.discount_limit else self.discount
            self.discount = subtotal if self.discount > subtotal else self.discount
        elif promo.discount_type == 2:
            self.shipping_fee = 0
        self.total_amount = self.cal_total_amounts()
        self.save()

        promo.used_count += 1
        promo.total_count_limit -= 1
        promo.save()
    
    def remove_promo(self):
        self.promo.used_count -= 1
        self.promo.total_count_limit += 1

        if self.promo.discount_type == 0:
            self.discount = 0
        elif self.promo.discount_type == 1:
            self.discount = 0
        elif self.promo.discount_type == 2:
            self.shipping_fee = self.cal_shipping_fee()
        self.promo.save()
        self.promo = None
        self.promo_code = None
        self.total_amount = self.cal_total_amounts()
        self.save()


    def admin_status_description(self):
        if self.status == 0:
            return '等待顧客確認運送資料'
        elif self.status == 1 and self.payment == 0:
            if self.remittance_account:
                return '顧客已填寫匯款帳號：' + str(self.remittance_account)
            else:
                return '等待顧客填寫匯款帳號'
        elif self.status == 2:
            return '已確認收到付款'
        elif self.status == 3:
            return '已出貨'
        else:
            return self.get_status_display()

    def customer_status_description(self):
        if self.status == 0:
            return '感謝您！您的訂單已成立！\n請填寫運送資料並送出。'
        elif self.status == 1 and self.payment == 0:
            if self.remittance_account:
                return '請稍候！我們會盡快核對款項並出貨！'
            else:
                return '運送資料已送出！\n當您匯款完成後，請填寫匯款帳戶末五碼。'
        elif self.status == 2:
            return '我們已確認您的付款，將盡快安排出貨！'
        elif self.status == 3:
            return '好消息！您的訂單已出貨！'
        elif self.status == 4:
            return '您的訂單已完成！'
        else:
            return self.get_status_display()

    def customer_short_status_description(self):
        if self.status == 0:
            return '請填寫運送資料'
        elif self.status == 1 and self.payment == 0:
            if self.remittance_account:
                return '正在核對款項'
            else:
                return '請填寫匯款帳戶'
        elif self.status == 2:
            return '已確認您的付款'
        elif self.status == 3:
            return '已出貨'
        elif self.status == 4:
            return '已完成'
        else:
            return self.get_status_display()

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    item_name = models.CharField(max_length=200)
    unit_price = models.IntegerField(default=0)
    amount = models.IntegerField(default=1)
    product = models.ForeignKey(Product, null=True, on_delete=models.SET_NULL)

WebStore/products/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    class Meta:
        verbose_name_plural = "categories"
    
    name = models.CharField(max_length=200, verbose_name='類別名稱')

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='類別')
    name = models.CharField(max_length=200, verbose_name='名稱')
    utility = models.CharField(max_length=200, verbose_name='用途')
    ingredient = models.CharField(max_length=200, verbose_name='成分')
    description = models.TextField(blank=True, verbose_name='概覽')
    unit_price = models.IntegerField(default=0, verbose_name='單價')
    is_sellable = models.BooleanField(default=True, verbose_name='上架')
    inventory_quantity = models.IntegerField(default=0, verbose_name='庫存')
    cover_image = models.ImageField(blank=True, verbose_name='封面照片')

    def __str__(self):
        return self.name

class Image(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='產品')
    image = models.ImageField(verbose_name='照片')

WebStore/order/forms.py
from django.forms import ModelForm
from .models import Order

class ShippingDataForm(ModelForm):
    class Meta:
        model = Order
        fields = ['user_name', 'user_gender', 'user_contact_phone_no', 'shipping_postal_code', 'shipping_address']


class PromoCodeForm(ModelForm):
    class Meta:
        model = Order
        fields = ['promo_code']

WebStore/products/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Product
from administration.models import Configuration

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'products/index.html'

    def get_queryset(self):
        return Product.objects.filter(is_sellable=True)

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['config'] = Configuration.objects.first()
        return context

class DetailView(generic.DetailView):
    model = Product
    template_name = 'products/detail.html'

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context['config'] = Configuration.objects.first()
        return context

    

WebStore/templates/administration/category_detail.html
{% extends 'administration/product_base.html' %}
{% block content %}

<div class="card">
    <div class="card-top-section">
        <div class="row title">
            {{ category }}
        </div>
        <div class="row function">
            <form action="{% url 'administration:category_update' category.id %}" method="get">
                <input class="button normal-btn" type="submit" value="編輯">
            </form>
            <form action="{% url 'administration:category_delete' category.id %}" method="get">
                <input class="button normal-btn" type="submit" value="刪除">
            </form>
        </div>
    </div>
    <div class="card-section">
        <div class="row sub-title">
            內容
        </div>
        <div class="row container-jcleft">
            <div class="attribute-name">
                產品種數
            </div>
            <div class="attribute">
                {{ category.product_set.all.count }} 種產品
            </div>
        </div>
    </div>
</div>

<div>
    <table class="stripe shadow">
        <thead>
            <tr>
                <th class="first_col">名稱</th>
                <th>類別</th>
                <th>單價</th>
                <th>庫存</th>
                <th>上架</th>
                <th class="last_col">動作</th>
            </tr>
        </thead>
        <tbody>
            {% for product in category.product_set.all %}
            <tr>
                <td class="first_col"><a href="{% url 'products:detail' product.id %}">{{ product }}</a></td>
                <td>{{ product.category }}</td>
                <td>NT$ {{ product.unit_price }}</td>
                <td {% if product.inventory_quantity < 10 %}class="red"{% endif %}>{{ product.inventory_quantity }}</td>
                <td>{% if product.is_sellable %}是{% else %}否{% endif %}</td>
                <td class="last_col">
                    <a class="button normal-btn" href="{% url 'administration:product_update' product.id %}">編輯</a>
                    <a class="button normal-btn" href="{% url 'administration:product_delete' product.id %}">刪除</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>


{% endblock %}

WebStore/templates/administration/category_update_form.html
{% extends 'administration/product_base.html' %}
{% block content %}


<div class="card">
    <div class="card-top-section">
        <div class="row title">
            {{ category }}
        </div>
        <div class="row function">
            <form action="{% url 'administration:category_delete' category.id %}" method="get">
                <input class="button normal-btn" type="submit" value="刪除">
            </form>
        </div>
    </div>
    <div class="card-section">
        <div class="row sub-title">
            編輯類別
        </div>
        <div>
            <form method="post">{% csrf_token %}
                {% for field in form %}
                <div class="container-jcleft row">
                    <div class="attribute-name">
                        {{ field.label }}
                    </div>
                    <div class="attribute">
                        {{ field }}
                    </div>
                </div>
                {% endfor %}
                <div class="container-jcleft row">
                    <input class="button normal-btn" type="submit" value="修改並儲存">
                </div>
            </form>
        </div>
    </div>
</div>


{% endblock %}

WebStore/templates/administration/order_detail.html
{% extends 'administration/order_base.html' %}
{% block content %}

<div class="card">
    <div class="card-top-section">
        <div class="row title">
            {{ order }}
        </div>
        <div class="row status">
            {{ order.admin_status_description }}
        </div>
        <div class="row function">
            <form action="{% url 'administration:order_next_step' order.id %}" method="post">{% csrf_token %}
                <input type="hidden" name="current_page" value="order_detail">
            {% if order.status == 1 and order.payment == 0 %}
                {% if order.remittance_account %}
                <input type="hidden" name="next_status" value="2">
                <input class="button normal-btn" type="submit" value="確認收到付款">
                {% endif %}
            {% elif order.status == 2 %}
                <input type="hidden" name="next_status" value="3">
                <input class="button normal-btn" type="submit" value="已出貨">
            {% elif order.status == 3 %}
                <input type="hidden" name="next_status" value="4">
                <input class="button normal-btn" type="submit" value="已完成">
            {% endif %}
            </form>
            <form action="{% url 'administration:order_update' order.id %}" method="get">
                <input class="button normal-btn" type="submit" value="編輯">
            </form>
        </div>
    </div>
    <div class="card-section">
        <div class="row sub-title">
            運送及付款
        </div>
        <div class="row container-jcleft">
            <div class="attribute-name">
                收件人
            </div>
            <div class="attribute">
                {{ order.user_name }} {{ order.get_user_gender_display }}
            </div>
        </div>
        <div class="row container-jcleft">
            <div class="attribute-name">
                收件地址
            </div>
            <div class="attribute">
                {{ order.shipping_postal_code }} {{ order.shipping_address }}
            </div>
        </div>
        <div class="row container-jcleft">
            <div class="attribute-name">
                付款方式
            </div>
            <div class="attribute">
                {{ order.get_payment_display }}
            </div>
        </div>
        <div class="row container-jcleft">
            <div class="attribute-name green">
                總金額
            </div>
            <div class="attribute green">
                NT$ {{ order.total_amount }}
            </div>
        </div>
        <div class="row container-jcleft">
            <div class="attribute-name green">
                匯款帳號末五碼
            </div>
            <div class="attribute green">
                {{ order.remittance_account }}
            </div>
        </div>
        <div class="row container-jcleft">
            <div class="attribute-name">
                聯絡電話
            </div>
            <div class="attribute">
                {{ order.user_contact_phone_no }}
            </div>
        </div>
    </div>
    <div class="card-section">
        <div class="row sub-title">
            訂單內容
        </div>
        {% for order_item in order.orderitem_set.all %}
        <div class="row container-jcleft">
            <div class="attribute-name">
                <a href="{% url 'products:detail' order_item.product.id %}">{{ order_item.item_name }}</a>
            </div>
            <div class="attribute">
                {{ order_item.amount }}
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="card-section">
        <div class="row sub-title">
            備註
        </div>
        <div class="row container-jcleft">
            <div class="attribute-name">
                優惠代碼
            </div>
            <div class="attribute">
                {{ order.promo_code }}
            </div>
        </div>
        <div class="row container-jcleft">
            <div class="attribute-name">
                優惠
            </div>
            <div class="attribute">
                -NT$ {{ order.discount }}
            </div>
        </div>
        <div class="row container-jcleft">
            <div class="attribute-name">
                運費
            </div>
            <div class="attribute">
                NT$ {{ order.shipping_fee }}
            </div>
        </div>
        <div class="row container-jcleft">
            <div class="attribute-name">
                訂購人電子郵件信箱
            </div>
            <div class="attribute">
                {{ order.user.email }}
            </div>
        </div>
        <div class="row container-jcleft">
            <div class="attribute-name">
                訂單成立時間
            </div>
            <div class="attribute">
                {{ order.timestamp }}
            </div>
        </div>
    </div>
</div>

<!-- <h1>Order {{ order.id }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<p>{{ order.user }}</p>
<p>{{ order.user_name }}</p>
<p>{{ order.get_user_gender_display }}</p>
<p>{{ order.user_contact_phone_no }}</p>
<p>{{ order.shipping_postal_code }}</p>
<p>{{ order.shipping_address }}</p>
<p>${{ order.shipping_fee }}</p>
<p>${{ order.total_amount }}</p>
<p>{{ order.get_status_display }}</p>
<p>{{ order.get_payment_display }}</p>
<p>{{ order.remittance_account }}</p>
<p>{{ order.is_canceled }}</p>
<p>{{ order.timestamp }}</p>

<ol>
{% for order_item in order.orderitem_set.all %}
    <li>
        <p>{{ order_item.item_name }}</p>
        <p>${{ order_item.unit_price }} * {{ order_item.amount }}</p>
    </li>
{% endfor %}
</ol>

<form action="{% url 'administration:order_next_step' order.id %}" method="post">{% csrf_token %}
    <input type="hidden" name="current_page" value="order_detail">
{% if order.status == 1 and order.payment == 0 %}
    {% if order.remittance_account %}
        <input type="hidden" name="next_status" value="2">
        <input type="submit" value="確認收到付款">
    {% else %}
        正在等待顧客填寫匯款帳號 
    {% endif %}
{% elif order.status == 2 %}
    <input type="hidden" name="next_status" value="3">
    <input type="submit" value="已出貨">
{% elif order.status == 3 %}
    <input type="hidden" name="next_status" value="4">
    <input type="submit" value="已完成">
{% endif %}
</form> -->


{% endblock %}

WebStore/templates/administration/product_base.html
{% extends 'administration_base.html' %}
{% block page-content %}

<div class="top-nav">
    <nav>
        <a href="{% url 'administration:products' %}" class="{{ subactive_all }}">所有產品</a>
    </nav>
    <nav>
        <a href="{% url 'administration:product_create' %}" class="{{ subactive_create }}">新增產品</a>
    </nav>
    <nav>
        <a href="{% url 'administration:categories' %}" class="{{ subactive_cat_all }}">所有類別</a>
    </nav>
    <nav>
        <a href="{% url 'administration:category_create' %}" class="{{ subactive_cat_create }}">新增類別</a>
    </nav>
</div>

<div class="content">
    {% block content %}
    {% endblock %}
</div>

{% endblock %}

WebStore/templates/administration/product_index.html
{% extends 'administration/product_base.html' %}
{% block content %}

<div>
    <table class="stripe shadow">
        <thead>
            <tr>
                <th class="first_col">名稱</th>
                <th>類別</th>
                <th>單價</th>
                <th>庫存</th>
                <th>上架</th>
                <th class="last_col">動作</th>
            </tr>
        </thead>
        <tbody>
            {% for product in object_list %}
            <tr>
                <td class="first_col"><a href="{% url 'products:detail' product.id %}">{{ product }}</a></td>
                <td>{{ product.category }}</td>
                <td>NT$ {{ product.unit_price }}</td>
                <td {% if product.inventory_quantity < 10 %}class="red"{% endif %}>{{ product.inventory_quantity }}</td>
                <td>{% if product.is_sellable %}是{% else %}否{% endif %}</td>
                <td class="last_col">
                    <a class="button normal-btn" href="{% url 'administration:product_update' product.id %}">編輯</a>
                    <a class="button normal-btn" href="{% url 'administration:product_delete' product.id %}">刪除</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>







<!-- <h1>All products</h1>

<a href="{% url 'administration:product_create' %}">Add</a>
<ol>
{% for product in object_list %}
    <li>
        <a href="{% url 'products:detail' product.id %}">{{ product }}</a>
        <a href="{% url 'administration:product_update' product.id %}">Edit</a>
        <a href="{% url 'administration:product_delete' product.id %}">Delete</a>
    </li>
{% endfor %}
</ol> -->


{% endblock %}

WebStore/templates/administration/promo_base.html
{% extends 'administration_base.html' %}
{% block page-content %}

<div class="top-nav">
    <nav>
        <a href="{% url 'administration:promos' %}" class="{{ subactive_all }}">所有優惠碼</a>
    </nav>
    <nav>
        <a href="{% url 'administration:promo_create' %}" class="{{ subactive_create }}">新增優惠碼</a>
    </nav>
</div>

<div class="content">
    {% block content %}
    {% endblock %}
</div>

{% endblock %}