WebStore/order/urls.py
from django.urls import path

from . import views

app_name = 'order'
urlpatterns = [
    path('cart/', views.cart, name='cart'),
    path('cart-item-edit/', views.cart_item_edit, name='cart_item_edit'),
    path('<int:product_id>/edit-cart-item/', views.cart_item_edit, name='cart_item_edit'),
    path('', views.IndexView.as_view(), name='index'),
    # path('<int:order_id>/', views.order_detail, name='detail'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('create/', views.order_create, name='create'),
    path('next-step/', views.next_step, name='next_step'),
    path('<int:pk>/edit-remittance-account/', views.EditRemittanceAccount.as_view(), name='edit_remittance_account'),
    path('<int:order_id>/promo-apply/', views.promo_apply, name='promo_apply'),
    path('<int:order_id>/promo-remove/', views.promo_remove, name='promo_remove'),
]

WebStore/products/urls.py
from django.urls import path

from . import views

app_name = 'products'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
]

WebStore/order/models.py
from datetime import datetime
from django.db import models
from django.conf import settings
from products.models import Product
from administration.models import Configuration
from django.utils import timezone


# Create your models here.
class CartItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    amount = models.IntegerField(default=1)

    def __str__(self):
        return str(self.product) + '(' + str(self.amount) + ')'

    def is_valid(self):
        return self.amount <= self.product.inventory_quantity and self.product.is_sellable

    def total_amounts(self):
        return self.product.unit_price * self.amount


class Promo(models.Model):
    DISCOUNT_TYPE_CHOICES = ((0, '總金額折價'), (1, '總金額打折'), (2, '免運費'))
    HAS_LIMIT_CHOICES = ((0, '無'), (1, '有'))

    code = models.CharField(max_length=32, unique=True, verbose_name='優惠代碼')
    used_count = models.IntegerField(default=0, verbose_name='使用次數')
    
    # Discount Type
    discount_type = models.IntegerField(default=0, choices=DISCOUNT_TYPE_CHOICES, verbose_name='優惠類型')
    discount_amount = models.IntegerField(default=0, verbose_name='折價金額')
    discount_ratio = models.DecimalField(default=0.9, max_digits=3, decimal_places=2, verbose_name='打折（比例）')
    discount_limit = models.IntegerField(default=100, verbose_name='最高折價上限')
    
    # Limitations
    has_total_amount_limit = models.IntegerField(default=0, choices=HAS_LIMIT_CHOICES, verbose_name='消費滿額才可用限制')
    total_amount_limit = models.IntegerField(default=0, verbose_name='消費滿此金額可用')
    
    has_total_count_limit = models.IntegerField(default=0, choices=HAS_LIMIT_CHOICES, verbose_name='使用次數限制')
    total_count_limit = models.IntegerField(default=10, verbose_name='剩餘使用次數')
    
    has_time_limit = models.IntegerField(default=0, choices=HAS_LIMIT_CHOICES, verbose_name='使用時間限制')
    time_limit_start = models.DateTimeField(default=timezone.now, verbose_name='開始有效時間')
    time_limit_expire = models.DateTimeField(default=timezone.now, verbose_name='截止有效時間')
    
    def __str__(self):
        return str(self.code)

    def usage_description(self):
        return self.total_amount_limit_description() + \
               self.discount_type_description() + \
               self.time_limit_description() + \
               self.total_count_limit_description()

    def discount_type_description(self):
        ret = ''
        if self.discount_type == 0:
            ret += '消費金額折扣 NT$' + str(self.discount_amount)
        elif self.discount_type == 1:
            ratio_digits1 = ['零', '一', '二', '三', '四', '五', '六', '七', '八', '九']
            ratio_digits2 = ['', '一', '二', '三', '四', '五', '六', '七', '八', '九']
            discount_str = str(self.discount_ratio)
            ratio_str = ratio_digits1[int(discount_str[2])] + ratio_digits2[int(discount_str[3])] + '折'
            ret += '消費金額' + ratio_str
            ret += '，折抵金額上限NT$ ' + str(self.discount_limit)
            print(str(self.discount_ratio)[2])
        elif self.discount_type == 2:
            ret += '免運費'
        return ret + '。'

    def total_amount_limit_description(self):
        ret = ''
        if self.has_total_amount_limit == 1:
            ret += '消費金額滿NT$ ' + str(self.total_amount_limit)
        else:
            ret += '不限消費金額'
        return ret + '可使用。'

    def time_limit_description(self):
        ret = '使用期限'
        if self.has_time_limit == 1:
            ret += '自' + str(self.time_limit_start) + '至' + str(self.time_limit_expire) + '止'
        else:
            ret += '無限制'
        return ret + '。'

    def total_count_limit_description(self):
        ret = ''
        if self.has_total_count_limit == 1:
            ret += str(self.total_count_limit)
        else:
            ret += '無限制'
        return ret

class Order(models.Model):
    GENDER_CHOICES = ((0, '先生'), (1, '女士'))
    STATUS_CHOICES = ((0, '已初始'), (1, '已成立'), (2, '已確認收到付款'), (3, '已出貨'), (4, '已完成'),
                      (5, '已申請退回'), (6, '已收到退回商品'), (7, '已退款'))
    PAYMENT_CHOICES = ((0, 'ATM匯款'),)
    
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL, verbose_name='使用者')
    user_name = models.CharField(max_length=100, verbose_name='收件人')
    user_gender = models.IntegerField(default=0, choices=GENDER_CHOICES, verbose_name='稱謂')
    user_contact_phone_no = models.CharField(max_length=20, verbose_name='聯絡電話')
    shipping_postal_code = models.CharField(max_length=5, verbose_name='郵遞區號')
    shipping_address = models.CharField(max_length=200, verbose_name='收件地址')
    shipping_fee = models.IntegerField(default=60, verbose_name='運費')
    total_amount = models.IntegerField(verbose_name='總金額')
    status = models.IntegerField(default=0, choices=STATUS_CHOICES, verbose_name='狀態')
    payment = models.IntegerField(default=0, choices=PAYMENT_CHOICES, verbose_name='付款方式')
    remittance_account = models.CharField(blank=True, max_length=5, verbose_name='匯款帳號末五碼')
    is_canceled = models.BooleanField(default=False, verbose_name='已取消')
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name='成立時間')
    promo = models.ForeignKey(Promo, null=True, on_delete=models.SET_NULL, verbose_name='優惠碼')
    promo_code = models.CharField(max_length=32, null=True, verbose_name='優惠代碼')
    discount = models.IntegerField(default=0, verbose_name='優惠')


    def __str__(self):
        return '訂單 ' + str(self.id)

    def cal_shipping_fee(self):
        config = Configuration.objects.first()
        discount_shipping_fee = config.discount_shipping_fee
        if self.cal_subtotal() < discount_shipping_fee:
            return config.shipping_fee
        else:
            return 0

    def cal_subtotal(self):
        subtotal = 0
        for item in self.orderitem_set.all():
            subtotal += item.total_amounts()
        return subtotal

    def cal_total_amounts(self):
        total_amounts = self.shipping_fee
        total_amounts += self.cal_subtotal()
        total_amounts -= self.discount
        return total_amounts if total_amounts > 0 else 0

    def can_use(self, promo):
        if promo.has_total_amount_limit == 1:
            if self.cal_subtotal() < promo.total_amount_limit:
                return False

        if promo.has_time_limit == 1:
            now = timezone.now()
            if not (promo.time_limit_start <= now <= promo.time_limit_expire):
                return False

        if promo.has_total_count_limit == 1:
            if promo.total_count_limit <= 0:
                return False

        return True

    def apply_promo(self, promo):
        if self.promo is not None:
            self.remove_promo()
        
        subtotal = self.cal_subtotal()
        self.promo = promo
        self.promo_code = promo.code
        if promo.discount_type == 0:
            self.discount = promo.discount_amount
            self.discount = subtotal if self.discount > subtotal else self.discount
        elif promo.discount_type == 1:
            self.discount = self.cal_subtotal() * (1 - promo.discount_ratio)
            self.discount = promo.discount_limit if self.discount > promo.discount_limit else self.discount
            self.discount = subtotal if self.discount > subtotal else self.discount
        elif promo.discount_type == 2:
            self.shipping_fee = 0
        self.total_amount = self.cal_total_amounts()
        self.save()

        promo.used_count += 1
        promo.total_count_limit -= 1
        promo.save()
    
    def remove_promo(self):
        self.promo.used_count -= 1
        self.promo.total_count_limit += 1

        if self.promo.discount_type == 0:
            self.discount = 0
        elif self.promo.discount_type == 1:
            self.discount = 0
        elif self.promo.discount_type == 2:
            self.shipping_fee = self.cal_shipping_fee()
        self.promo.save()
        self.promo = None
        self.promo_code = None
        self.total_amount = self.cal_total_amounts()
        self.save()


    def admin_status_description(self):
        if self.status == 0:
            return '等待顧客確認運送資料'
        elif self.status == 1 and self.payment == 0:
            if self.remittance_account:
                return '顧客已填寫匯款帳號：' + str(self.remittance_account)
            else:
                return '等待顧客填寫匯款帳號'
        elif self.status == 2:
            return '已確認收到付款'
        elif self.status == 3:
            return '已出貨'
        else:
            return self.get_status_display()

    def customer_status_description(self):
        if self.status == 0:
            return '感謝您！您的訂單已成立！\n請填寫運送資料並送出。'
        elif self.status == 1 and self.payment == 0:
            if self.remittance_account:
                return '請稍候！我們會盡快核對款項並出貨！'
            else:
                return '運送資料已送出！\n當您匯款完成後，請填寫匯款帳戶末五碼。'
        elif self.status == 2:
            return '我們已確認您的付款，將盡快安排出貨！'
        elif self.status == 3:
            return '好消息！您的訂單已出貨！'
        elif self.status == 4:
            return '您的訂單已完成！'
        else:
            return self.get_status_display()

    def customer_short_status_description(self):
        if self.status == 0:
            return '請填寫運送資料'
        elif self.status == 1 and self.payment == 0:
            if self.remittance_account:
                return '正在核對款項'
            else:
                return '請填寫匯款帳戶'
        elif self.status == 2:
            return '已確認您的付款'
        elif self.status == 3:
            return '已出貨'
        elif self.status == 4:
            return '已完成'
        else:
            return self.get_status_display()

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    item_name = models.CharField(max_length=200)
    unit_price = models.IntegerField(default=0)
    amount = models.IntegerField(default=1)
    product = models.ForeignKey(Product, null=True, on_delete=models.SET_NULL)

WebStore/order/forms.py
from django.forms import ModelForm
from .models import Order

class ShippingDataForm(ModelForm):
    class Meta:
        model = Order
        fields = ['user_name', 'user_gender', 'user_contact_phone_no', 'shipping_postal_code', 'shipping_address']


class PromoCodeForm(ModelForm):
    class Meta:
        model = Order
        fields = ['promo_code']

WebStore/templates/order/cart.html
{% extends 'base.html' %}
{% block content %}

<div class="caption"">
    購物車
</div>


{% if not cart_items %}
<div class="message tacenter">
    <div class="big-message">
        您的購物車中沒有商品。
    </div>
</div>
{% else %}
<div class="message tacenter">
    <div class="big-message">
        以下是您購物車中的商品 NT$ {{ total_amounts }}
    </div>
    <div class="shipping-fee-message">
        運費 NT$ {{ config.shipping_fee }}，消費金額滿 NT$ {{ config.discount_shipping_fee }}免運費。
    </div>
    <div class="function">
        {% if not is_not_valid %}
            <a class="create-order button" href="{% url 'order:create' %}">成立訂單</a>
        {% endif %}
    </div>
</div>

<div class="product-items">
    {% for item in cart_items %}
        <div class="product-item">
            <div class="container-jcleft row">
                <div class="product-name">
                    <a href="{% url 'products:detail' item.product.id %}">{{ item.product }}</a>
                </div>
                <div class="product-amount-price taright container-jcleft">
                    <div class="product-amount">
                        {{ item.amount }}
                    </div>
                    <div class="product-price">
                        NT$ {{ item.total_amounts }}
                    </div>
                </div>
            </div>
            <div class="container-jcright row function">
                {% if item.amount < item.product.inventory_quantity %}
                    <form action="{% url 'order:cart_item_edit' %}" method="post">{% csrf_token %}
                        <input type="hidden" name="product_id" value="{{ item.product.id }}">
                        <input type="hidden" name="amount" value="1">
                        <input type="submit" class="button" value="+">
                    </form>    
                {% elif item.amount > item.product.inventory_quantity %}
                    庫存不足
                {% endif %}
                <form action="{% url 'order:cart_item_edit' %}" method="post">{% csrf_token %}
                    <input type="hidden" name="product_id" value="{{ item.product.id }}">
                    <input type="hidden" name="amount" value="-1">
                    <input type="submit" class="button" value="-">
                </form>
                <form action="{% url 'order:cart_item_edit' %}" method="post">{% csrf_token %}
                    <input type="hidden" name="product_id" value="{{ item.product.id }}">
                    <input type="hidden" name="amount" value="-{{ item.amount }}">
                    <input type="submit" class="button" value="移除">
                </form>
            </div>
        </div>
    {% endfor %}
</div>

<div class="total">
    <div class="container-jcright row shipping-fee">
        <div class="total-left taright">
            運費
        </div>
        <div class="total-right taright">
            {% if shipping_fee == 0 %}
            此筆訂單免運費
            {% else %}
            NT$ {{ shipping_fee }}
            {% endif %}
        </div>
    </div>
    <div class="container-jcright row total-amounts">
        <div class="total-left taright">
            總金額
        </div>
        <div class="total-right taright">
            NT$ {{ total_amounts }}
        </div>
    </div>
    <div class="container-jcright row function">
        {% if not is_not_valid %}
            <a class="create-order button" href="{% url 'order:create' %}">成立訂單</a>
        {% else %}
            現在無法成立訂單
        {% endif %}
    </div>
</div>
{% endif %}



<!-- <h1>Cart</h1>

<ol>
{% for item in cart_items %}
    <li>
        <a href="{% url 'products:detail' item.product.id %}">{{ item.product }}</a>
        <p>${{ item.product.unit_price }} * {{ item.amount }}</p>
        <p>{{ item.product.inventory_quantity }} </p>
        {% if item.amount < item.product.inventory_quantity %}
            <form action="{% url 'order:cart_item_edit' %}" method="post">{% csrf_token %}
                <input type="hidden" name="product_id" value="{{ item.product.id }}">
                <input type="hidden" name="amount" value="1">
                <input type="submit" value="+">
            </form>
        {% elif item.amount > item.product.inventory_quantity %}
            <p>庫存不足</p>
        {% endif %}
        <form action="{% url 'order:cart_item_edit' %}" method="post">{% csrf_token %}
            <input type="hidden" name="product_id" value="{{ item.product.id }}">
            <input type="hidden" name="amount" value="-1">
            <input type="submit" value="-">
        </form>
        <form action="{% url 'order:cart_item_edit' %}" method="post">{% csrf_token %}
            <input type="hidden" name="product_id" value="{{ item.product.id }}">
            <input type="hidden" name="amount" value="-{{ item.amount }}">
            <input type="submit" value="Remove">
        </form>
    </li>
{% endfor %}
</ol>

{% if not is_not_valid %}
    <a href="{% url 'order:create' %}">Create order</a>
{% endif %} -->

{% endblock %}

WebStore/templates/order/detail.html
{% extends 'base.html' %}
{% block content %}

<div class="caption"">
    {{ order }}
</div>

{% if not order %}
<div class="message tacenter">
    <div class="big-message">
        {{ error_message }}
    </div>
</div>
{% else %}
<div class="message tacenter">
    <div class="big-message">
        {{ order.customer_status_description }}
    </div>
</div>

{% if promo_editable %}
<div class="product-info">
    <div class="title">
        優惠
    </div>
    <div class="container-jcleft row">
        <div class="attribute-name">
            優惠代碼
        </div>
        <div class="attribute">
            {% if order.promo_code %}{{ order.promo_code }}{% endif %}
            <a class="create-order button" href="{% url 'order:promo_apply' order.id %}">{% if order.promo_code %}更改{% else %}填寫{% endif %}</a>
            {% if order.promo_code %}<a class="create-order button" href="{% url 'order:promo_remove' order.id %}">移除</a>{% endif %}
        </div>
    </div>
</div>
{% endif %}

{% if remittance_account_editable %}
<div class="product-info">
    <div class="title">
        收款帳號
    </div>
    <div class="container-jcleft row">
        <div class="attribute-name">
            帳戶名稱
        </div>
        <div class="attribute">
            {{ config.manager_receiving_account_name }}
        </div>
    </div>
    <div class="container-jcleft row">
        <div class="attribute-name">
            銀行及代碼
        </div>
        <div class="attribute">
            {{config.manager_bank_code}} {{ config.manager_bank_name }}
        </div>
    </div>
    <div class="container-jcleft row">
        <div class="attribute-name">
            帳號
        </div>
        <div class="attribute">
            {{ config.manager_receiving_account }}
        </div>
    </div>
    <div class="container-jcleft row">
        <div class="attribute-name">
            說明
        </div>
        <div class="attribute">
           請將NT$ {{ order.total_amount }}匯款至此帳戶。如您已匯款，請至下方填寫您的匯款帳戶末五碼，我們會儘速確認。
        </div>
    </div>
</div>
{% endif %}

<div class="product-info">
    <div class="title">
        運送資料
    </div>
    {% if shipping_data_form %}
    <form action="{% url 'order:next_step' %}" method="post">{% csrf_token %}
        <input class="create-order button" type="submit" value="確認並送出">
        <input type="hidden" name="order_id" value="{{ order.id }}">
        {% for field in shipping_data_form %}
        <div class="container-jcleft row">
            <div class="attribute-name">
                {{ field.label }}
            </div>
            <div class="attribute">
                {{ field }}
            </div>
        </div>
        {% endfor %}
    </form>
    {% else %}
    <div class="container-jcleft row">
        <div class="attribute-name">
            收件人
        </div>
        <div class="attribute">
            {{ order.user_name }} {{ order.get_user_gender_display }}
        </div>
    </div>
    <div class="container-jcleft row">
        <div class="attribute-name">
            聯絡電話
        </div>
        <div class="attribute">
            {{ order.user_contact_phone_no }}
        </div>
    </div>
    <div class="container-jcleft row">
        <div class="attribute-name">
            收件地址
        </div>
        <div class="attribute">
            {{ order.shipping_postal_code }} {{order.shipping_address}}
        </div>
    </div>
    {% endif %}
</div>

<div class="product-info">
    <div class="title">
        付款
    </div>
    <div class="container-jcleft row">
        <div class="attribute-name">
            付款方式
        </div>
        <div class="attribute">
            {{ order.get_payment_display }}
        </div>
    </div>
    <div class="container-jcleft row">
        <div class="attribute-name">
            匯款帳號末五碼
        </div>
        <div class="attribute">
            {{ order.remittance_account }}
            {% if remittance_account_editable %}
            <a class="create-order button" href="{% url 'order:edit_remittance_account' order.id %}">{% if order.remittance_account %}編輯{% else %}填寫{% endif %}</a>
            {% endif %}
        </div>
    </div>
    {% if order.promo_code %}
    <div class="container-jcleft row">
        <div class="attribute-name">
            優惠代碼
        </div>
        <div class="attribute">
            {{ order.promo_code }}：
            {% if order.promo %}{{ order.promo.discount_type_description }}{% endif %}
        </div>
    </div>
    {% endif %}
</div>

<div class="product-info">
    <div class="title">
        訂單內容
    </div>
    {% for order_item in order.orderitem_set.all %}
    <div class="product-item">
        <div class="container-jcleft row">
            <div class="product-name">
                <a href="{% url 'products:detail' order_item.product.id %}">{{ order_item.item_name }}</a>
            </div>
            <div class="product-amount-price taright container-jcleft">
                <div class="product-amount">
                    {{ order_item.amount }}
                </div>
                <div class="product-price">
                    NT$ {{ order_item.total_amounts }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <div class="total">
        <div class="container-jcright row subtotal">
            <div class="total-left taright">
                小計
            </div>
            <div class="total-right taright">
                NT$ {{ order.cal_subtotal }}
            </div>
        </div>
        <div class="container-jcright row shipping-fee {% if order.shipping_fee == 0 %}promo{% endif %}">
            <div class="total-left taright">
                運費
            </div>
            <div class="total-right taright">
                {% if order.shipping_fee == 0 %}
                此筆訂單免運費
                {% else %}
                NT$ {{ order.shipping_fee }}
                {% endif %}
            </div>
        </div>
        {% if order.discount != 0 %}
        <div class="container-jcright row promo">
            <div class="total-left taright">
                優惠
            </div>
            <div class="total-right taright">
                -NT$ {{order.discount}}
            </div>
        </div>
        {% endif %}
        <div class="container-jcright row total-amounts">
            <div class="total-left taright">
                總金額
            </div>
            <div class="total-right taright">
                NT$ {{ order.total_amount }}
            </div>
        </div>
    </div>
</div>
{% endif %}


<!-- <h1>Order {{ order.id }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% if message %}<p><strong>{{ message }}</strong></p>{% endif %}
{% if order %}
    {% if shipping_data_form %}
    <form action="{% url 'order:next_step' %}" method="post">{% csrf_token %}
        <input type="hidden" name="order_id" value="{{ order.id }}">
        {% for field in shipping_data_form %}
            <div class="fieldWrapper">
                {{ field.errors }}
                {{ field.label_tag }} {{ field }}
            </div>
        {% endfor %}
    {% else %}
            <p>{{ order.user_name }}</p>
            <p>{{ order.get_user_gender_display }}</p>
            <p>{{ order.user_contact_phone_no }}</p>
            <p>{{ order.shipping_postal_code }}</p>
            <p>{{ order.shipping_address }}</p>
    {% endif %}

            <p>${{ order.shipping_fee }}</p>
            <p>${{ order.total_amount }}</p>
            <p>{{ order.get_status_display }}</p>
            <p>{{ order.get_payment_display }}</p>

            <p>{{ order.remittance_account }}</p>
    {% if remittance_account_editable %}
        <a href="{% url 'order:edit_remittance_account' order.id %}">{% if order.remittance_account %}編輯{% else %}填寫{% endif %}匯款帳號末五碼</a>
    {% endif %}

            <p>{{ order.timestamp }}</p>

    <ol>
    {% for order_item in order.orderitem_set.all %}
        <li>
            <p>{{ order_item.item_name }}</p>
            <p>${{ order_item.unit_price }} * {{ order_item.amount }}</p>
        </li>
    {% endfor %}
    </ol>

    {% if shipping_data_form %}
        <input type="submit" value="下一步">
    </form>
    {% endif %} -->

{% endif %}

{% endblock %}

WebStore/templates/order/index.html
{% extends 'base.html' %}
{% block content %}


<div class="caption"">
    我的訂單
</div>

<div class="message tacenter">
    <div class="big-message">
        以下是您的所有訂單。
    </div>
</div>

<div class="product-info">
    <div class="title">
        訂單
    </div>
    {% for order in object_list %}
        <div class="product-item">
            <div class="container-jcleft row">
                <div class="product-name">
                    <a href="{% url 'order:detail' order.id %}">{{ order }}</a>
                </div>
                <div class="order-detail taright container-jcleft">
                    <div class="order-payment">
                        {{ order.get_payment_display }}
                    </div>
                    <div class="order-status">
                        {{ order.customer_short_status_description }}
                    </div>
                    <div class="order-total-amount">
                        NT$ {{ order.total_amount }}
                    </div>
                    <div class="order-view">
                        <a href="{% url 'order:detail' order.id %}">查看更多</a>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>



<!-- <h1>Your Orders</h1>

<ol>
{% for order in object_list %}
    <li>
        <a href="{% url 'order:detail' order.id %}">Order {{ order.id }}</a>
    </li>
{% endfor %}
</ol>
 -->
{% endblock %}

WebStore/templates/order/promo_update_form.html
{% extends 'base.html' %}
{% block content %}

<div class="caption"">
    訂單 {{ order.id }}
</div>

<div class="message tacenter">
    <div class="big-message">
        請填寫優惠代碼。
    </div>
    <div class="shipping-fee-message">
        {{ error_message }}
    </div>
</div>

<div class="product-info">
    <div class="title">
        優惠代碼
    </div>
    <form method="post">{% csrf_token %}
        {% for field in form %}
            <div class="container-jcleft row">
                <div class="attribute-name">
                    {{ field.label }}
                </div>
                <div class="attribute">
                    {{ field }}
                </div>
            </div>
        {% endfor %}
        <div class="container row">
            <div>
                <input class="create-order button" type="submit" value="確定使用">
            </div>
        </div>
    </form>
</div>




{% endblock %} 

WebStore/templates/order/remittance_account_update_form.html
{% extends 'base.html' %}
{% block content %}

<div class="caption"">
    訂單 {{ order.id }}
</div>

{% if not order %}
<div class="message tacenter">
    <div class="big-message">
        {{ error_message }}
    </div>
</div>
{% else %}
<div class="message tacenter">
    <div class="big-message">
        請填寫匯款帳號。
    </div>
</div>

<div class="product-info">
    <div class="title">
        匯款帳號
    </div>
    <form method="post">{% csrf_token %}
        {% for field in form %}
            <div class="container-jcleft row">
                <div class="attribute-name">
                    {{ field.label_tag }}
                </div>
                <div class="attribute">
                    {{ field }}
                </div>
            </div>
        {% endfor %}
        <div class="container row">
            <div>
                <input class="create-order button" type="submit" value="確認並送出">
            </div>
        </div>
    </form>
</div>

{% endif %}


<!-- <h1>Order {{ order.id }}</h1>
<h2>填寫匯款帳號</h2>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>

{% endblock %} -->